FROM apache/airflow:2.9.0

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-docker \
    apache-airflow==2.9.0 \
    boto3>=1.38.13 \
    click>=8.1.8 \
    elasticsearch>=9.0.1 \
    fastapi>=0.115.12 \
    feast>=0.48.0 \
    fsspec>=2025.3.2 \
    huggingface-hub>=0.30.2 \
    ipython>=8.36.0 \
    langchain-community>=0.3.23 \
    langchain-openai>=0.3.16 \
    langchain>=0.3.25 \
    langgraph>=0.4.1 \
    minio>=7.1.0 \
    numpy>=1.22.0 \
    pandas>=2.2.3 \
    protobuf>=6.0.0 \
    psycopg2-binary>=2.9.10 \
    pyarrow>=20.0.0 \
    pydantic-settings>=2.9.1 \
    pydantic>=2.11.4 \
    pymilvus>=2.5.8 \
    sentence-transformers>=4.1.0
