FROM python:3.9-slim AS compile-image

ARG MLFLOW_VERSION

# Define virtual env
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# RUN /opt/venv/bin/pip install mlflow==${MLFLOW_VERSION} psycopg2-binary charset-normalizer==2.1.0
RUN pip install mlflow==${MLFLOW_VERSION} psycopg2-binary charset-normalizer==2.1.0

FROM python:3.9-alpine AS runtime-image

LABEL maintainer="quandv"
LABEL organization="mlopsvn"

COPY --from=compile-image /opt/venv /opt/venv

WORKDIR /mlflow/

# Set environment variables
ENV PATH="/opt/venv/bin:$PATH"

EXPOSE 5000

# Ref: https://github.com/mlflow/mlflow/issues/6274#issuecomment-1196106372
CMD mlflow server \
    --backend-store-uri ${BACKEND_STORE_URI} \
    --serve-artifacts \
    --host 0.0.0.0 \
    --port 5000